name: Robot Framework Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: bash

      - name: Executar testes
        run: |
          robot --outputdir logs ${{ github.workspace }}/tests/
        shell: bash

      - name: Publicar resultados dos testes
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: logs/
